### PR TITLE
Refactor using Flask-RESTX and Swagger

### PR DESCRIPTION
**Pull request by Yuhao-Fan**

### CODE REVIEW

**Comment by Yvonne98XU** [comment]
Just a small thought. Have you tried to change the DATABASE_URI in docker-compose.yml file into postgresql://postgres:pgs3cr3t@postgres:5432/postgres, it seems that you have changed it in workflow.yml. Or opposite of it, change the workflow to make it pairs.

**Comment by Yuhao-Fan** [comment]
> Just a small thought. Have you tried to change the DATABASE_URI in docker-compose.yml file into postgresql://postgres:pgs3cr3t@postgres:5432/postgres, it seems that you have changed it in workflow.yml. Or opposite of it, change the workflow to make it pairs.

seems it is not be the reason

**Comment by zqf0722** [comment]
Congrats on passing the tests

**Review by zqf0722 — APPROVED** [review]
Congrats on passing the tests.

**Comment by Yvonne98XU** [comment]
Good job! Then I'll close that bug PR fixing. Congrats!!

**Pull request merged**
