### PR TITLE
Swagger

### PR DESCRIPTION
**Pull request by Yuhao-Fan**
added api models 
prepare for refactoring

### CODE REVIEW

**Comment by Yuhao-Fan** [comment]
> Please keep test coverage above 95%

coverage must drop after refactoring, right?

**Comment by zqf0722** [comment]
> > Please keep test coverage above 95%
> 
> coverage must drop after refactoring, right?

Yeah, but it needs to be above 95%.

**Comment by zqf0722** [comment]
Please add tests and merge the PR.

**Comment by Yuhao-Fan** [comment]
> Please add tests and merge the PR.

OK, I will try to write it in swagger1.

**Comment by zqf0722** [comment]
> 

Then what's the plan for this PR? Should we just close this one if you are not going to change it any way.

**Pull request closed without merging**
